// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package db

import (
	"context"
)

type Querier interface {
	CheckUserRepeat(ctx context.Context, arg *CheckUserRepeatParams) (int64, error)
	CreateUser(ctx context.Context, arg *CreateUserParams) (*CreateUserRow, error)
	DeleteUser(ctx context.Context, id int64) error
	DeleteUserById(ctx context.Context, id int64) error
	GetUserById(ctx context.Context, id int64) (*GetUserByIdRow, error)
	GetUserByName(ctx context.Context, username string) (*GetUserByNameRow, error)
	GetUsers(ctx context.Context) ([]*GetUsersRow, error)
	ListNameNum(ctx context.Context, username string) (int64, error)
	ListNum(ctx context.Context) (int64, error)
	ListUserInfo(ctx context.Context, arg *ListUserInfoParams) ([]*ListUserInfoRow, error)
	SearchUserByName(ctx context.Context, arg *SearchUserByNameParams) ([]*SearchUserByNameRow, error)
	UpdatePassword(ctx context.Context, arg *UpdatePasswordParams) error
	UpdateUser(ctx context.Context, arg *UpdateUserParams) error
	UpdateUserAvatar(ctx context.Context, arg *UpdateUserAvatarParams) error
}

var _ Querier = (*Queries)(nil)
